### ISSUE TITLE
Crash when preloading

### ISSUE THREAD

**Issue by sjanuary** [IBM-APM/node-ibmapm-embed#2]
Appmetrics supports preloading (i.e. starting an application with `node -r appmetrics/start app.js`) but this is now broken since adding IBM-APM as a dependency.

```
[Wed Jun  6 13:48:30 2018] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 4.0.0.201806061347 (Agent Core 3.2.6)
[2018-06-06 13:48:31.525] [ERROR] config.js - failed to instance plugin./lib/plugins/BAMPlugin.js
[2018-06-06 13:48:31.528] [ERROR] config.js - TypeError: Cannot read property 'paths' of undefined
    at initAppGuid (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/util.js:116:32)
    at Object.module.exports.init (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/util.js:27:9)
    at init (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/BAMPlugin.js:325:12)
    at Object.<anonymous> (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/BAMPlugin.js:296:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
[2018-06-06 13:48:31.531] [ERROR] config.js - failed to instance plugin./lib/plugins/BIPlugin.js
[2018-06-06 13:48:31.531] [ERROR] config.js - TypeError: Cannot read property 'paths' of undefined
    at initAppGuid (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/util.js:116:32)
    at Object.module.exports.init (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/util.js:27:9)
    at init (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/BIPlugin.js:572:12)
    at Object.<anonymous> (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/plugins/BIPlugin.js:355:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/restclient/httpsender.js:27
        var name = inst.Name();
                        ^

TypeError: Cannot read property 'Name' of undefined
    at /home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/restclient/httpsender.js:27:25
    at Array.forEach (<anonymous>)
    at Object.module.exports.checkReadyStatus (/home/sian/appmetrics/node_modules/ibmapm-embed/lib/ibm_apm_restclient/lib/restclient/httpsender.js:26:32)
    at Object.<anonymous> (/home/sian/appmetrics/node_modules/ibmapm-embed/index.js:97:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

```

**Comment by shiyanf** [comment]
fixed in https://www.npmjs.com/package/ibmapm-embed/v/1.0.13

**Comment by sjanuary** [comment]
@shiyanf Thank you for fixing this so quickly
